### ISSUE TITLE
A little more help with example for using patch with docker and plex

### ISSUE THREAD

**Issue by kiwijunglist** [keylase/nvidia-patch#446]
Hi

I have nvidia-docker2 working with plex

Docker-compose.yaml
```
  plex:
    image: lscr.io/linuxserver/plex
    runtime: nvidia
    environment:
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
   ... etc ...
```

```
mike@manitoba:~/docker/config$ docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
Mon Oct 25 10:14:50 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P1000        Off  | 00000000:01:00.0 Off |                  N/A |
| 44%   55C    P0    N/A /  N/A |    980MiB /  4040MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

I am having trouble following your instructions for getting the patched drives working with plex in docker, is it possible to provide a more detailed example using docker-compose?

Thanks
Mike
